
[[section]]
key = []
children = [
    { 
        key = ["global_registry"],
        comment = "Set the global registry for PNPM (and NPM if configured). Empty uses https://registry.npmjs.org/"
        value = "",
    },
    {
        key = ["install_npm"],
        comment = "Also install NPM with PNPM. '*' to install the default version. Empty will not install NPM.",
        value = "",
    }
]

[[section]]
key = ["default-version"]
comment = """
The default engine/package-manager versions to install when syncing
empty-string = not-specifed = default
"""
children = [
    { key = ["node"], value = "" },
]
