version: '3'

includes:
  common:
    taskfile: ./mono-dev/task/common.yaml
    flatten: true
    optional: true

  build:          { taskfile: ./packages/build,           dir: ./packages/build,          internal: true }
  cli:            { taskfile: ./packages/cli,             dir: ./packages/cli,            internal: true }
  corelib:        { taskfile: ./packages/corelib,         dir: ./packages/corelib,        internal: true }
  registry:       { taskfile: ./packages/registry,        dir: ./packages/registry,       internal: true }
  shaftim:        { taskfile: ./packages/shaftim,         dir: ./packages/shaftim,        internal: true }
  shaftim-build:  { taskfile: ./packages/shaftim-build,   dir: ./packages/shaftim-build,  internal: true }
  shutil-lfmt:    { taskfile: ./packages/shutil-lfmt,     dir: ./packages/shutil-lfmt,    internal: true }
  shutil-n:       { taskfile: ./packages/shutil-n,        dir: ./packages/shutil-n,       internal: true }
  shutil-viopen:  { taskfile: ./packages/shutil-viopen,   dir: ./packages/shutil-viopen,  internal: true }
  shutil-vipath:  { taskfile: ./packages/shutil-vipath,   dir: ./packages/shutil-vipath,  internal: true }
  shutil-which:   { taskfile: ./packages/shutil-which,    dir: ./packages/shutil-which,  internal: true }
  win-envedit:    { taskfile: ./packages/win-envedit,     dir: ./packages/win-envedit,    internal: true }

tasks:
  install:
    - rm -rf packages/mono-dev
    - rm -rf mono-dev
    - git clone https://github.com/Pistonight/mono-dev --depth 1 mono-dev
    - echo 'fn main() {}' > packages/shaftim/main.rs
  install-cargo-extra-tools:
    alias: [icets]
    cmds:
      - cargo install lfmt --git https://github.com/Pistonite/shellutils
  check:
    - task: corelib:check
    - task: registry:check
    - task: cli:check
    - task: shaftim-build:check
    - task: shaftim:check
    - task: shutil-lfmt:check
    - task: shutil-n:check
    - task: shutil-viopen:check
    - task: shutil-vipath:check
    - task: shutil-which:check
    - task: win-envedit:check
    - cargo run --bin lfmt -- -c
  fix:
    - task: registry:fix
    - cargo fmt
    - cargo run --bin lfmt
  test:
    - task: corelib:test
    - task: registry:test

  clean:
    - task: registry:clean
    - cargo clean

  shaft:
    - task: run-build
    - cargo run --bin shaft -- {{.CLI_ARGS}}

  run-build:
    - cargo run --bin shaft-build

  build-shutil:
    - cargo build --bin lfmt
    - cargo build --bin viopen
    - cargo build --bin n
    - cargo build --bin vipath 
    - cargo build --bin which 

  upgrade:
    - cargo upgrade
