version: '3'

includes:
  common:
    taskfile: ./packages/mono-dev/task/common.yaml
    flatten: true
    optional: true

  # cli:            { taskfile: ./packages/cli,             dir: ./packages/cli,            internal: true }
  corelib:        { taskfile: ./packages/corelib,         dir: ./packages/corelib,        internal: true }
  registry:       { taskfile: ./packages/registry,        dir: ./packages/registry,       internal: true }
  registry-build: { taskfile: ./packages/registry-build,  dir: ./packages/registry-build, internal: true }

tasks:
  install:
    - rm -rf packages/mono-dev
    - mkdir -p packages
    - git clone https://github.com/Pistonight/mono-dev --depth 1 packages/mono-dev
  install-cargo-extra-tools:
    alias: [icets]
    cmds:
      - cargo install lfmt --git https://github.com/Pistonite/shellutils
  check:
    - task: corelib:check
    - task: registry-build:check
    - task: registry:check
    # - task: cli:check
    - lfmt -c
  fix:
    - task: registry:fix
    - cargo fmt
    - lfmt
  test:
    - task: corelib:test
    
  clean:
    - task: registry:clean
    - cargo clean
