
# Variables
#$v_kbd_backlight=framework::kbd_backlight

$va_kdb_backlight_timeout_cmd=brightnessctl -sd framework::kbd_backlight set 0
$va_kdb_backlight_resume_cmd=brightnessctl -rd framework::kbd_backlight
general {
    # command that runs for loginctl lock-session
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Monitor backlight
listener {
    timeout = 600
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}
# Keyboard backlight
listener { 
    timeout = 600
    on-timeout = $va_kdb_backlight_timeout_cmd
    on-resume = $va_kdb_backlight_resume_cmd
}
# Turn off monitor
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}
listener {
    timeout = 905
    on-timeout = loginctl lock-session
}
listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
