input-field {
    monitor =
    halign = center
    valign = center
    position = 0, -240 
    size = 400, 50
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.11
    dots_center = true
    outer_color = rgb(74c7ec)
    inner_color = rgba(00000000)
    font_color = rgb(cdd6f4)
    font_size = 18
    fail_text = Access Denied
    fail_color = rgb(f38ba8)
    check_color = rgba(74c7ec00)
    placeholder_text =
    fade_on_empty = false
    hide_input = false
}
