use std::{
    path::{Path, PathBuf},
    sync::Arc,
};

use cu::pre::*;

pub struct PythonStandaloneEnvironment {
    /// The CPython version string, for example 3.14.8
    version: String,
    /// The installation directory
    ///
    /// The layout is as follows:
    /// - /python<version> - where we pass as install-dir to UV
    ///   for it to download and extract the python interpreter
    ///   and install packages
    /// - pyproject.toml - a uv project that tracks the required pip packages.
    ///   The `managed` dependency group is managed by the package that
    ///   requested this environment, and `dependencies` are added by the user.
    ///   Tracked so when the python interpreter is bumped, it can install
    ///   a new interpreter and recover the packages
    /// - uv.lock - generated by uv
    /// - pipi script (ps1/shell) - uv add the arguments to the project,
    ///   no arg uv syncs the environment with the project. Both install
    ///   into the standalone python instead of a .venv
    /// - python script - shim to invoke the python interpreter
    location: PathBuf,

    /// Managed requirement specs, written to the `managed` dependency
    /// group in pyproject.toml
    managed_requirements: Vec<String>,

    /// Message printed when running pip directly, not through our script
    externally_managed_message: String,
}

impl PythonStandaloneEnvironment {
    /// Create the environment structure bound to the specific version and location
    pub fn new(
        location: impl AsRef<Path>,
        version: &str,
        managed_requirements: Vec<String>,
        externally_managed_message: String,
    ) -> cu::Result<Self> {
        let mut parts = version.split('.');
        let Some(major) = parts.next() else {
            cu::bail!("invalid python version - missing major");
        };
        let Some(minor) = parts.next() else {
            cu::bail!("invalid python version - missing minor");
        };
        let Some(patch) = parts.next() else {
            cu::bail!("invalid python version - missing patch");
        };
        if parts.next().is_some() {
            cu::bail!("invalid python version - too many parts");
        }
        let major = cu::check!(cu::parse::<u32>(major), "invalid python major version")?;
        let minor = cu::check!(cu::parse::<u32>(minor), "invalid python minor version")?;
        let patch = cu::check!(cu::parse::<u32>(patch), "invalid python patch version")?;

        let version = format!("{major}.{minor}.{patch}");
        let location = location.as_ref().normalize()?;
        cu::debug!(
            "created python standalone environment handle: version={version}, location: '{}'",
            location.display()
        );

        Ok(Self {
            version,
            location,
            managed_requirements,
            externally_managed_message,
        })
    }

    /// Get the path to the python interpreter
    pub fn python_interpreter(&self) -> cu::Result<PathBuf> {
        let dist_root = self.python_dist_root()?;
        Ok(self.python_executable_from_dist_root(&dist_root))
    }

    /// Ensure the environment is set-up. Does not install dependencies
    pub fn ensure(&self, bar: Option<Arc<cu::ProgressBar>>) -> cu::Result<()> {
        if self.python_dist_root().is_err() {
            self.install(bar)?;
        }
        Ok(())
    }

    fn install(&self, bar: Option<Arc<cu::ProgressBar>>) -> cu::Result<()> {
        let uv = cu::check!(
            cu::which("uv"),
            "uv is required to install python standalone environment. please run 'shaft sync uv'"
        )?;
        // ensure they can be read before doing the install
        let user_deps = cu::check!(
            self.read_user_requirements(),
            "error reading user dependencies from pyproject.toml"
        )?;
        // remove old /python... directories
        let mut to_delete = vec![];
        if self.location.exists() {
            for e in cu::fs::read_dir(&self.location)? {
                let Ok(e) = e else {
                    continue;
                };
                if !e.path().is_dir() {
                    continue;
                }
                if e.file_name().to_string_lossy().starts_with("python") {
                    to_delete.push(e.path());
                }
            }
            match &bar {
                None => {
                    for d in to_delete {
                        cu::debug!("removing previous python distribution: {}", d.display());
                        cu::fs::rec_remove(&d)?;
                    }
                }
                Some(bar) => {
                    let bar = bar
                        .child("remove previous python distribution")
                        .total(to_delete.len())
                        .percentage(false)
                        .eta(false)
                        .spawn();
                    for d in to_delete {
                        cu::progress!(bar, "{}", d.display());
                        cu::fs::rec_remove(&d)?;
                        cu::progress!(bar += 1);
                    }
                }
            }
        }
        if let Some(bar) = &bar {
            cu::progress!(bar, "setting up a standalone python environment");
        }
        let install_dir = self.python_install_dir();
        let (child, bar2, _) = uv
            .command()
            .add(cu::args![
                "python",
                "install",
                &self.version,
                "--install-dir", // point to our location as the root for UV to place distributions
                &install_dir,
                "--no-bin",      // do not add to path
                "--no-registry"  // do not edit registry on Windows
            ])
            .stdin_null()
            .stdoe(
                cu::pio::spinner(format!("installing python {}", self.version))
                    .configure_spinner(|b| b.parent(bar.clone())),
            )
            .spawn()?;
        child.wait_nz()?;
        bar2.done();

        let mut dist_name = None;

        // there should be one directory in the target that is not symlink
        // or hidden (uv keeps its own files like .temp there)
        for e in cu::fs::read_dir(&install_dir)? {
            let e = e?;
            let ft = e.file_type()?;
            if ft.is_symlink() || !ft.is_dir() {
                continue;
            }

            let name = e.file_name().into_utf8()?;
            if name.starts_with('.') {
                continue;
            }
            match &dist_name {
                Some(x) => {
                    cu::bail!(
                        "uv installed multiple distributions, this is not expected: {x} and {name}"
                    );
                }
                None => {
                    cu::debug!("installed python distribution name is {name}");
                    if let Some(bar) = &bar {
                        cu::progress!(bar, "installed {name}");
                    }
                    dist_name = Some(name);
                }
            }
        }

        let Some(dist_name) = dist_name else {
            cu::bail!("unexpected: uv did not place installed distribution");
        };

        cu::fs::write(install_dir.join("PYTHON_DIST_NAME.txt"), &dist_name)?;

        let dist_root = cu::check!(
            self.python_dist_root(),
            "unexpected: failed to get dist root after installation"
        )?;
        // replace the externally managed message
        let externally_managed_content = format!(
            "[externally-managed]\nError={}",
            self.externally_managed_message
        );
        let externally_managed_file = if cfg!(windows) {
            cu::path!(&dist_root / "Lib" / "EXTERNALLY-MANAGED")
        } else {
            let python_lib = format!("python{}", self.version_without_patch());
            cu::path!(&dist_root / "lib" / python_lib / "EXTERNALLY-MANAGED")
        };
        cu::fs::write(externally_managed_file, externally_managed_content)?;

        let path = self.location.join("pyproject.toml");
        let content = include_str!("pyproject.toml")
            .replace("!!PYTHON_VERSION!!", &self.version)
            .replace("!!USER_REQUIREMENTS!!", &toml_string_array(&user_deps))
            .replace(
                "!!MANAGED_REQUIREMENTS!!",
                &toml_string_array(&self.managed_requirements),
            );
        cu::fs::write(path, content)?;

        cu::fs::write(self.location.join(".gitignore"), "*")?;

        self.write_scripts(&dist_root)?;

        Ok(())
    }

    /// Write the pipi and python scripts with the paths of this environment
    fn write_scripts(&self, dist_root: &Path) -> cu::Result<()> {
        let python = self.python_executable_from_dist_root(dist_root);
        let python = quote_path_for_script(&python)?;
        let dist_root = quote_path_for_script(dist_root)?;
        let project = quote_path_for_script(&self.location)?;

        let (pipi_template, python_template, ext) = if cfg!(windows) {
            (include_str!("pipi.ps1"), include_str!("python.ps1"), ".ps1")
        } else {
            (include_str!("pipi.sh"), include_str!("python.sh"), "")
        };
        let pipi = pipi_template
            .replace("!!PYTHON_DIST!!", &dist_root)
            .replace("!!PROJECT!!", &project);
        let python = python_template.replace("!!PYTHON!!", &python);

        for (name, content) in [("pipi", pipi), ("python", python)] {
            let path = self.location.join(format!("{name}{ext}"));
            cu::fs::write(&path, content)?;
            crate::opfs::set_executable(&path)?;
        }

        Ok(())
    }

    /// Read `dependencies` in [project] from the existing pyproject.toml
    fn read_user_requirements(&self) -> cu::Result<Vec<String>> {
        let path = self.location.join("pyproject.toml");
        if !path.exists() {
            return Ok(vec![]);
        }
        let content = cu::fs::read_string(&path)?;
        let pyproject = cu::check!(
            toml::parse::<toml::Table>(&content),
            "failed to parse '{}'",
            path.display()
        )?;
        let Some(requirements) = pyproject.get("project").and_then(|x| x.get("dependencies"))
        else {
            return Ok(vec![]);
        };
        let Some(requirements) = requirements.as_array() else {
            cu::bail!(
                "project.dependencies in '{}' is not an array",
                path.display()
            );
        };
        requirements
            .iter()
            .map(|x| match x.as_str() {
                Some(x) => Ok(x.to_string()),
                None => cu::bail!(
                    "project.dependencies in '{}' should only contain strings",
                    path.display()
                ),
            })
            .collect()
    }

    /// The /python<version> directory at install root
    fn python_install_dir(&self) -> PathBuf {
        self.location.join(format!("python{}", self.version))
    }

    /// The python distribution root.
    ///
    /// It should have python.exe (windows) or bin/python<major>.<minor> (non-windows)
    /// Since the version is dynamic, it uses a cache file PYTHON_DIST_NAME.txt
    #[cu::context("the standalone python environment is not configured correctly")]
    pub fn python_dist_root(&self) -> cu::Result<PathBuf> {
        let install_dir = self.python_install_dir();
        let dist_name_file = install_dir.join("PYTHON_DIST_NAME.txt");
        let Ok(dist_name) = cu::fs::read_string(dist_name_file) else {
            cu::bail!("could not read PYTHON_DIST_NAME.txt");
        };
        // remove newline that could be added by editors
        let dist_name = dist_name.trim();
        let dist_root = cu::path!(install_dir / dist_name);
        if !dist_root.is_dir() {
            cu::bail!("could not read the directory specified in PYTHON_DIST_NAME");
        }
        let python = self.python_executable_from_dist_root(&dist_root);
        if !python.is_file() {
            cu::bail!("could not read python interpreter binary");
        }

        let (child, stdout) = python
            .command()
            .arg("--version")
            .stdout(cu::pio::string())
            .stdie_null()
            .spawn()?;
        child.wait_nz()?;
        let stdout = stdout.join()??;
        if format!("Python {}", self.version) != stdout.trim() {
            cu::bail!("unexpected --version output: {}", stdout.trim());
        }

        // interpreter verified
        Ok(dist_root)
    }

    fn version_without_patch(&self) -> &str {
        // the version is validated in constructor
        match self.version.rfind('.') {
            Some(i) => &self.version[..i],
            None => &self.version,
        }
    }

    fn python_executable_from_dist_root(&self, dist_root: &Path) -> PathBuf {
        if cfg!(windows) {
            cu::path!(&dist_root / "python.exe")
        } else {
            cu::path!(&dist_root / "bin" / format!("python{}", self.version_without_patch()))
        }
    }
}

/// Format the strings as a multi-line TOML array
fn toml_string_array(items: &[String]) -> String {
    if items.is_empty() {
        return "[]".to_string();
    }
    let mut out = String::from("[\n");
    for item in items {
        out.push_str("    ");
        out.push_str(&toml::Value::String(item.clone()).to_string());
        out.push_str(",\n");
    }
    out.push(']');
    out
}

/// Convert the path to a string to replace a placeholder inside single quotes
/// in the pipi and python scripts
fn quote_path_for_script(path: &Path) -> cu::Result<String> {
    let path = path.as_os_str().as_utf8()?;
    // a single quote cannot appear in a single-quoted string directly
    let path = if cfg!(windows) {
        path.replace('\'', "''")
    } else {
        path.replace('\'', r"'\''")
    };
    Ok(path)
}
