# generated by shaft - install packages into the standalone python environment
#
# usage:
#   pipi <args>...  uv add <args> - add the requirements to the project and install them
#   pipi            uv sync - sync the environment with the project
#
# to uninstall a package, remove it from the project's pyproject.toml and run pipi

# environment variables set here leak into the calling session, so restore them after
$oldProjectEnvironment = $env:UV_PROJECT_ENVIRONMENT
$oldPythonDownloads = $env:UV_PYTHON_DOWNLOADS
try {
    # install into the standalone python instead of a .venv
    $env:UV_PROJECT_ENVIRONMENT = '!!PYTHON_DIST!!'
    # never download another interpreter if the project does not match the standalone python
    $env:UV_PYTHON_DOWNLOADS = 'never'

    if ($args.Count -eq 0) {
        uv sync --project '!!PROJECT!!'
    } else {
        uv add --project '!!PROJECT!!' @args
    }
} finally {
    $env:UV_PROJECT_ENVIRONMENT = $oldProjectEnvironment
    $env:UV_PYTHON_DOWNLOADS = $oldPythonDownloads
}
exit $LASTEXITCODE
