#!/usr/bin/env sh
# generated by shaft - install packages into the standalone python environment
#
# usage:
#   pipi <args>...  uv add <args> - add the requirements to the project and install them
#   pipi            uv sync - sync the environment with the project
#
# to uninstall a package, remove it from the project's pyproject.toml and run pipi

# install into the standalone python instead of a .venv
export UV_PROJECT_ENVIRONMENT='!!PYTHON_DIST!!'
# never download another interpreter if the project does not match the standalone python
export UV_PYTHON_DOWNLOADS=never

if [ $# -eq 0 ]; then
    exec uv sync --project '!!PROJECT!!'
fi
exec uv add --project '!!PROJECT!!' "$@"
