source = ~/.config/hypr/hyprlock-share.conf 

background {
    monitor =
    path = ~/.config/hypr/paper-startup.png
    color = rgb(000000)
    blur_passes = 1
    blur_size = 2
}

animations {
    animation = fadeOut, 0
}
