[[section]]
key = ["windows"]
comment = "Options for Windows-specific settings"
children = [
    {
        key = ["prefer-gnu"],
        value = true,
        comment = """
For commands with compatibility for both DOS and GNU,
prefer GNU when ambiguous
"""
    },
    {
        key = ["cmd-mkdir"],
        value = true,
        comment = """
Add a doskey macro to make the mkdir command in CMD GNU-compatible.
(Essentially alias mkdir in CMD to mkdir -p)
"""
    }
]
