[core]
# Bumping this version will re-configure all installed packages
CONFIG_VERSION = "2"

[_7z]
REPO = "https://github.com/ip7z/7zip"
VERSION = "26.00"
'cfg(target_arch="aarch64")'.SHA = "92fac666911336f3bbf3d99fdc48ec36fe20ac7a4200556936e61a8076ae6493"
'cfg(target_arch="x86_64")'.SHA = "6fe18d5b3080e39678cabfa6cef12cfb25086377389b803a36a3c43236a8a82c"

[pwsh]
# using preview version to enable tilde (~) expansion
REPO = "https://github.com/PowerShell/PowerShell"
VERSION = "7.6.0-preview.6"
'cfg(target_arch="aarch64")'.SHA = '36dc90e7f0e7870b0970c9a58790de4de4217e65acafaf790e87b7c97d93649f'
'cfg(target_arch="x86_64")'.SHA = '481ce45bd9ebfab9a5b254a35f145fb6259bd452ae67d92ab1d231b6367987d9'

[cargo_binstall]
VERSION = "1.17.7"

[coreutils]
ALIAS_VERSION = "12"
eza.VERSION = "0.23.4"
uutils.VERSION = "0.6.0"
zip.VERSION = "3.0"
unzip.VERSION = "6.0"
tar.VERSION = "1.35"
which.VERSION = "2.23"
bash.VERSION = "5.3.9"
bash_cmp.VERSION = "2.17.0"
yay.VERSION = "12.5.7"

[shellutils]
ALIAS_VERSION = "8"
REPO = "https://github.com/Pistonite/shellutils"
COMMIT = "11ced9625f35ba68c4eb3197490d48ef284efb2d"
which.VERSION = "0.1.4"
viopen.VERSION = "0.2.0"
vipath.VERSION = "0.1.7"
n.VERSION = "0.1.1"
wsclip.VERSION = "0.1.7"
lfmt.VERSION = "0.1.6"

[git]
'cfg(windows)'.ALIAS_VERSION = "1"
'cfg(windows)'.VERSION = "2.52.0"
'cfg(target_os="linux")'.VERSION = "2.53.0"
delta.VERSION = "0.18.2"
CFG_VERSION = "2"

[perl]
'cfg(target_os="linux")'.VERSION = "5.42.0"

[curl]
'cfg(target_os="linux")'.VERSION = "8.18.0"
# Windows ships with curl.exe

[wget]
'cfg(target_os="linux")'.VERSION = "1.25.0"
'cfg(windows)'.REPO = "https://github.com/lifenjoiner/wget-for-windows"
'cfg(windows)'.VERSION = "1.25.0"
'cfg(windows)'.URL = "https://github.com/lifenjoiner/wget-for-windows/releases/download/v1.25.0.230-a13d0/wget-ucrt64-xp-openssl-lite_v1.25.0.230-a13d0_e2f4498e19fa63184014e3b9d2f071bbc1c6217b.7z"
'cfg(windows)'.SHA = "fd60911ec2d94857e55e574521e8cb247ff852b58a34348a829f7cd98a2530e7"

[fzf]
REPO = "https://github.com/junegunn/fzf"
VERSION = "0.70.0"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "eaa12ca2e072ef8e8f89ca3d961fd886e46fbbc254c0c85c4786d813416a95d5"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "7465a6738e2c844742df973459c7509aed2d10d7a72bfd6de201b867b4eda4cd"

[jq]
REPO = "https://github.com/jqlang/jq"
VERSION = "1.8.1"
'cfg(windows)'.SHA = "23cb60a1354eed6bcc8d9b9735e8c7b388cd1fdcb75726b93bc299ef22dd9334"

[task]
REPO = "https://github.com/go-task/task"
VERSION = "3.49.1"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "bacbc74ee6a1402179b62966f3e3f5b9047b6a6c2688c4ad3c08946b5a4cf731"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "725c551f699d4d6c0dc57bd8148f72bef8d5b2fb650d9c985f271a61522fd521"
'cfg(target_os="linux")'.SHA = "4e7d24f1bf38218aec8f244eb7ba671f898830f9f87b3c9b30ff1c09e3135576"

[bat]
VERSION = "0.26.1"

[dust]
VERSION = "1.2.4"

[fd]
VERSION = "10.4.1"

[rg]
VERSION = "15.1.0"

[websocat]
VERSION = "1.14.1"

[zoxide]
VERSION = "0.9.9"

[hack_font]
REPO = "https://github.com/ryanoasis/nerd-fonts"
VERSION_PACMAN = "3.4.0-2"
VERSION = "3.4.0"
SHA = "8ca33a60c791392d872b80d26c42f2bfa914a480f9eb2d7516d9f84373c36897"

[terminal]
'cfg(windows)'.CONFIG_VERSION = "8"
clink.REPO = "https://github.com/chrisant996/clink"
clink.VERSION = "1.9.17"
clink.SHA = "0f2e7b407b9e33d487b8f348a72310631a26db84c80ad8d25e617f953d976fa8"
clink.URL = "https://github.com/chrisant996/clink/releases/download/v1.9.17/clink.1.9.17.36e2ca.zip"
clink.WRAPPER_VERSION = "2"

[volta]
REPO = "https://github.com/volta-cli/volta"
VERSION = "2.0.2"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "a996918b7a7bf2af9ceffce005208943f4eeaf779757ca73f5dfaa91a0072ad7"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "d7678a485e2fc9b1a3f7e9da256d8b88a97d7e4c45e63701c4874f6c2a587e0f"
'cfg(target_os="linux")'.SHA = "6cec054c911fb925b629a09455775af6e95dc0f5694a4c28b63979ab9ef18037"
ALIAS_VERSION = "1"
pnpm.REPO = "https://github.com/pnpm/pnpm"
pnpm.VERSION = "10.31.0"
node.VERSION = "24"
yarn.VERSION = "4"

[uv]
ALIAS_VERSION = "1"
VERSION = "0.10.9"

[gnucc]
gcc.VERSION = "15.2.1"
binutils.VERSION = "2.46"
gdb.VERSION = "17.1"

[clang]
REPO = "https://github.com/llvm/llvm-project"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "446081c8bed99c74eae17b2274f99a2edf37256efbbffe8b8078ac1212efc132"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "2dd6a6c990865f98766dec58cce1cbfba48e5affc0098e5b1fff96c2f1d23e81"
'cfg(windows)'.LLVM_VERSION = "22.1.0"
'cfg(target_os="linux")'.LLVM_VERSION = "21.1.8"

[llvm_mingw]
REPO = "https://github.com/mstorsjo/llvm-mingw"
TAG = "20260224"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "026c4f0c0aa198056cd4670dc68126e5ca1cdd4ea2c73fab85667bf0881c6022"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "acbf018fc24e42c21c74bea1df83f77c1f3e23de7d69d7d73b1993b5954c97ba"
'cfg(windows)'.LLVM_VERSION = "22.1.0"


[cmake]
# this is official
REPO = "https://github.com/Kitware/CMake"
'cfg(windows)'.VERSION = "4.2.3"
'cfg(target_os="linux")'.VERSION = "4.2.3"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "751b206b1cf65151b72c525d26267c1d9beebf8fafc365ae00286571d9fd3ed9"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "eb4ebf5155dbb05436d675706b2a08189430df58904257ae5e91bcba4c86933c"

[ninja]
REPO = "https://github.com/ninja-build/ninja"
'cfg(windows)'.VERSION = "1.13.2"
'cfg(target_os="linux")'.VERSION = "1.13.2"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "e52f0bdef9dfb1003229dbd6508a508c4073fd017247002adc66e5e806cb0391"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "07fc8261b42b20e71d1720b39068c2e14ffcee6396b76fb7a795fb460b78dc65"

[starship]
VERSION = "1.24.2"
CFG_VERSION = "10"

[nvim]
REPO = "https://github.com/neovim/neovim"
VERSION = "0.11.6"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "67a4e1da1f0d99e71c5e7b2dfd95f8c34721bd8c139eec99bb3e9034c2766301"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "90fc6d7cdf3d3388737caab1e2c554aa24b468f3a5cc38ef63857ddf1103513c"
'cfg(target_os="linux")'.SHA = "2fc90b962327f73a78afbfb8203fd19db8db9cdf4ee5e2bef84704339add89cc"
NVIM_CFG = "8"

[tree_sitter]
VERSION = "0.26.6"
REPO = "https://github.com/tree-sitter/tree-sitter"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "ce44f5b3c5ebc72c4b51a9214b61ebbf480f9bc596343a19375d9ddabc1cf42b"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "76d52345b1ef0d1f1b3f4357b42f39bc521c0bf7e87c9e18664bbb71da1577b8"
'cfg(target_os="linux")'.SHA = "2b9595064a7d9dbe208c6f09f521d73061f8039e4ffcc2fd08979d249aeabb54"
