[core]
# Bumping this version will re-configure all installed packages
CONFIG_VERSION = "3"

[_7z]
REPO = "https://github.com/ip7z/7zip"
VERSION = "26.01"
SHA.__match__ = "opfs::cpu_arch()"
SHA.'opfs::CpuArch::Arm64' = "1fecf4e3407950939c8ffcc3e42e3039821997dea155301c75369474e5f15175"
SHA.'opfs::CpuArch::X64' = "d64a0468f5b5b0b0fc5b2188450bcd655b70809d97b1c4535f2884635094377d"

[pwsh]
# using preview version to enable tilde (~) expansion
REPO = "https://github.com/PowerShell/PowerShell"
VERSION = "7.7.0-preview.2"
SHA.__match__ = "opfs::cpu_arch()"
SHA.'opfs::CpuArch::Arm64' = "8d54e5c754ab34e8c979686854ff110d1f9a81d54d629b6f48cbda2b1f45699d"
SHA.'opfs::CpuArch::X64' = "9965153b4d3308dd5b3cb3d1a800b89b7b93a345b09f208e0f9b2123119b28e9"

[cargo_binstall]
VERSION = "1.19.1"

[coreutils]
ALIAS_VERSION = "14"
eza.VERSION = "0.23.4"
zip.VERSION = "3.0"
unzip.VERSION = "6.0"
tar.VERSION = "1.35"
which.VERSION = "2.25"
bash.VERSION = "5.3.12"
bash_cmp.VERSION = "2.17.0"
yay.VERSION = "12.6.0"
ms_coreutils.VERSION = "2026.5.29"
ms_coreutils.REPO = "https://github.com/microsoft/coreutils"
ms_coreutils.COMMIT = "e0dea0bffc58dd697f3ae60315f8579e2bf9b86f" # -- MUST BE MANUALLY PICKED! -- new utils/breaking changes likely to the setup process
uutils_sed.VERSION = "0.1.1"

[shellutils]
ALIAS_VERSION = "8"
which.VERSION = "0.1.5"
viopen.VERSION = "0.2.1"
vipath.VERSION = "0.1.8"
n.VERSION = "0.1.2"
wsclip.VERSION = "0.1.8"
lfmt.VERSION = "0.2.0"

[git]
'cfg(windows)'.ALIAS_VERSION = "1"
'cfg(windows)'.VERSION = "2.52.0"
'cfg(target_os="linux")'.VERSION = "2.54.0"
delta.VERSION = "0.19.2"
CFG_VERSION = "2"

[perl]
'cfg(target_os="linux")'.VERSION = "5.42.2"

[curl]
'cfg(target_os="linux")'.VERSION = "8.20.0"
# Windows ships with curl.exe

[wget]
'cfg(target_os="linux")'.VERSION = "1.25.0"
'cfg(windows)'.REPO = "https://github.com/lifenjoiner/wget-for-windows"
'cfg(windows)'.VERSION = "1.25.0"
'cfg(windows)'.URL = "https://github.com/lifenjoiner/wget-for-windows/releases/download/v1.25.0.230-a13d0/wget-ucrt64-xp-openssl-lite_v1.25.0.230-a13d0_e2f4498e19fa63184014e3b9d2f071bbc1c6217b.7z"
'cfg(windows)'.SHA = "fd60911ec2d94857e55e574521e8cb247ff852b58a34348a829f7cd98a2530e7"

[fzf]
REPO = "https://github.com/junegunn/fzf"
VERSION = "0.72.0"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "186af4f9d30434b4eb34d670312d96fb7886a10c4c1ce9c64453dd0fa19aedec"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "cce66ae7e442030334927bfbfd917690713e63d215aba93027f99807828fe239"

[jq]
REPO = "https://github.com/jqlang/jq"
VERSION = "1.8.1"
'cfg(windows)'.SHA = "23cb60a1354eed6bcc8d9b9735e8c7b388cd1fdcb75726b93bc299ef22dd9334"

[task]
REPO = "https://github.com/go-task/task"
VERSION = "3.51.1"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "d92bf9561a8a1db591487995eb76a08951de15134c40299a98d77460be4e4e1d"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "422d79dff5afd5a55fb46ae1cfacc7350ec96d4ef27a63a3ec77a5c30a7b0f03"
'cfg(target_os="linux")'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::Arm64' = "<unsupported>"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::X64' = "da7e92f0ff961ef2aae7cfecbad8d1fd2a08d7b09ba968673adf7ff389b243b5"

[bat]
VERSION = "0.26.1"

[dust]
VERSION = "1.2.4"

[fd]
VERSION = "10.4.2"

[rg]
VERSION = "15.1.0"

[websocat]
VERSION = "1.14.1"

[zoxide]
VERSION = "0.9.9"

[hack_font]
REPO = "https://github.com/ryanoasis/nerd-fonts"
VERSION_PACMAN = "3.4.0-2"
VERSION = "3.4.0"
SHA = "8ca33a60c791392d872b80d26c42f2bfa914a480f9eb2d7516d9f84373c36897"

[terminal]
'cfg(windows)'.CONFIG_VERSION = "10"
clink.REPO = "https://github.com/chrisant996/clink"
clink.VERSION = "1.9.23"
clink.SHA = "ef6102aea6f6350804c32428ce04ad82eb185b0387424f62fe0f6f1e8c19737d"
clink.URL = "https://github.com/chrisant996/clink/releases/download/v1.9.23/clink.1.9.23.37616c.zip"
clink.WRAPPER_VERSION = "3"

[volta]
REPO = "https://github.com/volta-cli/volta"
VERSION = "2.0.2"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "a996918b7a7bf2af9ceffce005208943f4eeaf779757ca73f5dfaa91a0072ad7"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "d7678a485e2fc9b1a3f7e9da256d8b88a97d7e4c45e63701c4874f6c2a587e0f"
'cfg(target_os="linux")'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::Arm64' = "<unsupported>"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::X64' = "6cec054c911fb925b629a09455775af6e95dc0f5694a4c28b63979ab9ef18037"
ALIAS_VERSION = "1"
pnpm.REPO = "https://github.com/pnpm/pnpm"
pnpm.VERSION = "11.2.1"
node.VERSION = "24"
yarn.VERSION = "4"

[uv]
ALIAS_VERSION = "1"
VERSION = "0.11.19"

[gnucc]
gcc.VERSION = "16.1.1"
binutils.VERSION = "2.46"
gdb.VERSION = "17.2"

[clang]
REPO = "https://github.com/llvm/llvm-project"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "841278d0f7e091653af22cea7643fbeba587f702edf19247713180036c5b4cdb"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "657343edf361ca463bd642e39c74b251c6338b96cdbd55ff277555298b027696"
'cfg(windows)'.LLVM_VERSION = "22.1.6"
'cfg(target_os="linux")'.LLVM_VERSION = "22.1.6"

[llvm_mingw]
REPO = "https://github.com/mstorsjo/llvm-mingw"
TAG = "20260519"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "7bb5e3c9964dc29555cababb55e69eea02a51e98e1240eb9513e6540c7bae0ea"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "72dbd6e64614e3b3401998992d1bd9c8ace29e74611d71c80309ea71c3fb26f9"
'cfg(windows)'.LLVM_VERSION = "22.1.6"


[cmake]
# this is official
REPO = "https://github.com/Kitware/CMake"
'cfg(windows)'.VERSION = "4.3.2"
'cfg(target_os="linux")'.VERSION = "4.3.3"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "42a2a88fc57e70d04a92f6eaaac2094241995f53584bc2afdae7e6ef982b3781"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "83d20c23f5c5f64b3b328785e35b23c532e33057a97ed6294acaca3781b78a01"

[ninja]
REPO = "https://github.com/ninja-build/ninja"
'cfg(windows)'.VERSION = "1.13.2"
'cfg(target_os="linux")'.VERSION = "1.13.2"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "e52f0bdef9dfb1003229dbd6508a508c4073fd017247002adc66e5e806cb0391"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "07fc8261b42b20e71d1720b39068c2e14ffcee6396b76fb7a795fb460b78dc65"

[starship]
VERSION = "1.25.1"
CFG_VERSION = "10"

[nvim]
REPO = "https://github.com/neovim/neovim"
VERSION = "0.12.2"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "ed3e2844708878221325b6f0fd07bbca06c01700d4c4f72f4a100b026e84dfd2"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "23fe150edbcc976eabe55092e1e9d2e5e237afde69553d170e936f776b405d53"
'cfg(target_os="linux")'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::Arm64' = "<unsupported>"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::X64' = "31cf85945cb600d96cdf69f88bc68bec814acbff50863c5546adef3a1bcef260"
NVIM_CFG = "13"

[tree_sitter]
VERSION = "0.26.9"
REPO = "https://github.com/tree-sitter/tree-sitter"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "77422e257649158b91296d340d8430b7a0b469df41734efc9b261f1a16a33e95"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "dbb5309fcc76eaeb4ec358fcb72ac2eae5cd653e12967246cc63f84038d16cd8"
'cfg(target_os="linux")'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::Arm64' = "<unsupported>"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::X64' = "9ce82137caa65864e7ca8b869fd391cef88c9bd2a01c4371b9c4dd26c2585efb"

[hyprland]
kitty.CFG_VERSION = "1"
kitty.VERSION = "0.47.1"

[framework16]
kbd_uleds.REPO = "https://github.com/paco3346/fw16-kbd-uleds"
kbd_uleds.COMMIT = "51af3af4b857edb73117898369fe4658d0113703"

[vcpkg]
REPO = "https://github.com/microsoft/vcpkg-tool"
VERSION = "2026-04-08"
source.REPO = "https://github.com/microsoft/vcpkg"
source.TAG = "2026.04.27"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "6828f600ddd9de0269e7c68d2d264abee37fa2a16cad86b14b8e91fe225d530b"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "f1edbf3a39de350e2bb065214fdc057111aa87a2e2ed9a7dcb8ddc86e17751b9"

