[core]
# Bumping this version will re-configure all installed packages
CONFIG_VERSION = "3"

[_7z]
REPO = "https://github.com/ip7z/7zip"
VERSION = "26.00"
SHA.__match__ = "opfs::cpu_arch()"
SHA.'opfs::CpuArch::Arm64' = "92fac666911336f3bbf3d99fdc48ec36fe20ac7a4200556936e61a8076ae6493"
SHA.'opfs::CpuArch::X64' = "6fe18d5b3080e39678cabfa6cef12cfb25086377389b803a36a3c43236a8a82c"

[pwsh]
# using preview version to enable tilde (~) expansion
REPO = "https://github.com/PowerShell/PowerShell"
VERSION = "7.6.0-preview.6"
SHA.__match__ = "opfs::cpu_arch()"
SHA.'opfs::CpuArch::Arm64' = "36dc90e7f0e7870b0970c9a58790de4de4217e65acafaf790e87b7c97d93649f"
SHA.'opfs::CpuArch::X64' = "481ce45bd9ebfab9a5b254a35f145fb6259bd452ae67d92ab1d231b6367987d9"

[cargo_binstall]
VERSION = "1.17.7"

[coreutils]
ALIAS_VERSION = "12"
eza.VERSION = "0.23.4"
uutils.VERSION = "0.6.0"
zip.VERSION = "3.0"
unzip.VERSION = "6.0"
tar.VERSION = "1.35"
which.VERSION = "2.23"
bash.VERSION = "5.3.9"
bash_cmp.VERSION = "2.17.0"
yay.VERSION = "12.5.7"

[shellutils]
ALIAS_VERSION = "8"
REPO = "https://github.com/Pistonite/shellutils"
COMMIT = "11ced9625f35ba68c4eb3197490d48ef284efb2d"
which.VERSION = "0.1.4"
viopen.VERSION = "0.2.0"
vipath.VERSION = "0.1.7"
n.VERSION = "0.1.1"
wsclip.VERSION = "0.1.7"
lfmt.VERSION = "0.1.6"

[git]
'cfg(windows)'.ALIAS_VERSION = "1"
'cfg(windows)'.VERSION = "2.52.0"
'cfg(target_os="linux")'.VERSION = "2.53.0"
delta.VERSION = "0.18.2"
CFG_VERSION = "2"

[perl]
'cfg(target_os="linux")'.VERSION = "5.42.0"

[curl]
'cfg(target_os="linux")'.VERSION = "8.18.0"
# Windows ships with curl.exe

[wget]
'cfg(target_os="linux")'.VERSION = "1.25.0"
'cfg(windows)'.REPO = "https://github.com/lifenjoiner/wget-for-windows"
'cfg(windows)'.VERSION = "1.25.0"
'cfg(windows)'.URL = "https://github.com/lifenjoiner/wget-for-windows/releases/download/v1.25.0.230-a13d0/wget-ucrt64-xp-openssl-lite_v1.25.0.230-a13d0_e2f4498e19fa63184014e3b9d2f071bbc1c6217b.7z"
'cfg(windows)'.SHA = "fd60911ec2d94857e55e574521e8cb247ff852b58a34348a829f7cd98a2530e7"

[fzf]
REPO = "https://github.com/junegunn/fzf"
VERSION = "0.70.0"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "eaa12ca2e072ef8e8f89ca3d961fd886e46fbbc254c0c85c4786d813416a95d5"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "7465a6738e2c844742df973459c7509aed2d10d7a72bfd6de201b867b4eda4cd"

[jq]
REPO = "https://github.com/jqlang/jq"
VERSION = "1.8.1"
'cfg(windows)'.SHA = "23cb60a1354eed6bcc8d9b9735e8c7b388cd1fdcb75726b93bc299ef22dd9334"

[task]
REPO = "https://github.com/go-task/task"
VERSION = "3.49.1"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "bacbc74ee6a1402179b62966f3e3f5b9047b6a6c2688c4ad3c08946b5a4cf731"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "725c551f699d4d6c0dc57bd8148f72bef8d5b2fb650d9c985f271a61522fd521"
'cfg(target_os="linux")'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::Arm64' = "<unsupported>"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::X64' = "4e7d24f1bf38218aec8f244eb7ba671f898830f9f87b3c9b30ff1c09e3135576"

[bat]
VERSION = "0.26.1"

[dust]
VERSION = "1.2.4"

[fd]
VERSION = "10.4.1"

[rg]
VERSION = "15.1.0"

[websocat]
VERSION = "1.14.1"

[zoxide]
VERSION = "0.9.9"

[hack_font]
REPO = "https://github.com/ryanoasis/nerd-fonts"
VERSION_PACMAN = "3.4.0-2"
VERSION = "3.4.0"
SHA = "8ca33a60c791392d872b80d26c42f2bfa914a480f9eb2d7516d9f84373c36897"

[terminal]
'cfg(windows)'.CONFIG_VERSION = "8"
clink.REPO = "https://github.com/chrisant996/clink"
clink.VERSION = "1.9.17"
clink.SHA = "0f2e7b407b9e33d487b8f348a72310631a26db84c80ad8d25e617f953d976fa8"
clink.URL = "https://github.com/chrisant996/clink/releases/download/v1.9.17/clink.1.9.17.36e2ca.zip"
clink.WRAPPER_VERSION = "2"

[volta]
REPO = "https://github.com/volta-cli/volta"
VERSION = "2.0.2"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "a996918b7a7bf2af9ceffce005208943f4eeaf779757ca73f5dfaa91a0072ad7"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "d7678a485e2fc9b1a3f7e9da256d8b88a97d7e4c45e63701c4874f6c2a587e0f"
'cfg(target_os="linux")'.SHA = "6cec054c911fb925b629a09455775af6e95dc0f5694a4c28b63979ab9ef18037"
ALIAS_VERSION = "1"
pnpm.REPO = "https://github.com/pnpm/pnpm"
pnpm.VERSION = "10.31.0"
node.VERSION = "24"
yarn.VERSION = "4"

[uv]
ALIAS_VERSION = "1"
VERSION = "0.10.9"

[gnucc]
gcc.VERSION = "15.2.1"
binutils.VERSION = "2.46"
gdb.VERSION = "17.1"

[clang]
REPO = "https://github.com/llvm/llvm-project"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "54897a70f7c4fa9d66cd1cb280a3a223a0c70f7abaee1322c78beeeb89af4682"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "186f17ebedf13bae2835b2c0d5111a2a469ac241e7fc6387c9ce4585d6ef56ed"
'cfg(windows)'.LLVM_VERSION = "22.1.1"
'cfg(target_os="linux")'.LLVM_VERSION = "22.1.1"

[llvm_mingw]
REPO = "https://github.com/mstorsjo/llvm-mingw"
TAG = "20260311"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "33cd916b991cbeb0b44bcb51f58c20c999f074410d2802afdbfbf5d8b51402ca"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "dd4c67d98959479c7be2fb6709ba074475991590848cb9d0eb2620be06b182e1"
'cfg(windows)'.LLVM_VERSION = "22.1.1"


[cmake]
# this is official
REPO = "https://github.com/Kitware/CMake"
'cfg(windows)'.VERSION = "4.3.0"
'cfg(target_os="linux")'.VERSION = "4.3.0"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "174cdb8a877ce9d27ce2e7bd5ed74e48b333fb87b82ed7962c6c2325d35065e1"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "0f664f44eeb5b35b77f83e0984459c0dfa70539bd215c54ae1059604fd4f77ea"

[ninja]
REPO = "https://github.com/ninja-build/ninja"
'cfg(windows)'.VERSION = "1.13.2"
'cfg(target_os="linux")'.VERSION = "1.13.2"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "e52f0bdef9dfb1003229dbd6508a508c4073fd017247002adc66e5e806cb0391"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "07fc8261b42b20e71d1720b39068c2e14ffcee6396b76fb7a795fb460b78dc65"

[starship]
VERSION = "1.24.2"
CFG_VERSION = "10"

[nvim]
REPO = "https://github.com/neovim/neovim"
VERSION = "0.11.6"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "67a4e1da1f0d99e71c5e7b2dfd95f8c34721bd8c139eec99bb3e9034c2766301"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "90fc6d7cdf3d3388737caab1e2c554aa24b468f3a5cc38ef63857ddf1103513c"
'cfg(target_os="linux")'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::Arm64' = "<unsupported>"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::X64' = "2fc90b962327f73a78afbfb8203fd19db8db9cdf4ee5e2bef84704339add89cc"
NVIM_CFG = "8"

[tree_sitter]
VERSION = "0.26.7"
REPO = "https://github.com/tree-sitter/tree-sitter"
'cfg(windows)'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(windows)'.SHA.'opfs::CpuArch::Arm64' = "e7ea8f67db49c288f697d89a5538860ea1c219c92dfc366010d00b8b19d54d7f"
'cfg(windows)'.SHA.'opfs::CpuArch::X64' = "5cea52c5e8000fbe56c41148dd3124fded2fe7cd0f66e4194bf92532905c55ff"
'cfg(target_os="linux")'.SHA.__match__ = "opfs::cpu_arch()"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::Arm64' = "<unsupported>"
'cfg(target_os="linux")'.SHA.'opfs::CpuArch::X64' = "4367a46bc8abbb8328d6efbeb26e86807af0a3a7e462548a3924f87289ee1e9c"
