version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true
    optional: true

tasks:
  install:
    - pnpm i @types/node --no-lockfile

  update:
    - node --experimental-strip-types update/main.mts {{.CLI_ARGS}}

  clean:
    - rm -f package.json package-lock.json pnpm-lock.yaml bun.lock
    - rm -rf node_modules
    - rm -rf update/temp
    - rm -rf update-metadata-temp

  check:
    - task: cargo:clippy-all
    - task: check-rustfmt
    - task: cargo:fmt-check

  check-rustfmt:
    - rustfmt --check -l $(find src/packages -name '*.rs') --edition 2024

  fix:
    - rustfmt $(find src/packages -name '*.rs') --edition 2024
    - task: cargo:fmt-fix

  test:
    - cargo test
