version: '3'

includes:
  cargo:
    taskfile: ../../mono-dev/task/cargo.yaml
    internal: true
    optional: true
  git:
    taskfile: ../../mono-dev/task/git.yaml
    internal: true
    optional: true

tasks:
  install:
    - pnpm i @types/node --no-lockfile

  update:
    - node --experimental-strip-types update/main.mts {{.CLI_ARGS}}

  clean:
    - rm -f package.json package-lock.json pnpm-lock.yaml bun.lock
    - rm -rf node_modules
    - rm -rf update/temp
    - rm -rf update-metadata-temp

  check:
    - task: cargo:clippy-all
    - task: cargo:rustfmt-check
      vars:
        PATH: src/packages
    - task: cargo:fmt-check
    - task: check-shutil-meta

  fix:
    - task: cargo:rustfmt-fix
      vars:
        PATH: src/packages
    - task: cargo:fmt-fix

  test:
    - cargo test

  check-shutil-meta:
    - node --experimental-strip-types update/main.mts shellutils
    - task: git:check-modification
      vars:
        CHECK_PATH: metadata.toml
        CHECK_MESSAGE: shellutils metadata is not up-to-date or uncommited changes in metadata

  copy-nvim:
    desc: Copy config directory from this machine (~/.config/nvim) to shaft. Only works on Unix
    vars:
      TARGET: src/packages/nvim/config
    cmds:
      - rm -rf {{.TARGET}}
      - cp -R ~/.config/nvim {{.TARGET}}
      - rm -rf {{.TARGET}}/.git
      - rm -rf {{.TARGET}}/claudecode.nvim
      - rm -rf {{.TARGET}}/lua/piston/cache
      - rm -f {{.TARGET}}/.gitignore
      - rm -f {{.TARGET}}/lazy-lock.json
      - rm -f {{.TARGET}}/lua/piston/config_gen.lua
      - CURRENT=$(grep -oP 'NVIM_CFG = "\K[0-9]+' metadata.toml) && sed -i "s/NVIM_CFG = \"$CURRENT\"/NVIM_CFG = \"$((CURRENT+1))\"/" metadata.toml
