name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  build-native:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: blacksmith-4vcpu-ubuntu-2404
          - image: blacksmith-4vcpu-windows-2025
          # - image: windows-11-arm
          #   target: arm64
    runs-on: ${{ matrix.image }}
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
          ecma-node: true
      - run: task run-build
      - run: cargo build --bin shaft
      - run: task build-shutil
      - run: task check
      - run: task test
  build-windows-arm-x64:
    runs-on: windows-11-arm
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
          rust-native: x64,arm64
      - run: task run-build
      - run: cargo build --bin shaft --target x86_64-pc-windows-msvc --features build-x64
