name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
          tool-cargo-install: lfmt=Pistonite/shellutils
      - run: task run-build
      - run: cargo build --bin shaft
      - run: task check
      - run: task test
  build-windows-x64:
    runs-on: blacksmith-4vcpu-windows-2025
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
      - run: task run-build
      - run: cargo build --bin shaft
  build-windows-arm-x64:
    runs-on: windows-11-arm
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
          rust-native: x64,arm64
      - run: task run-build
      - run: cargo build --bin shaft --target x86_64-pc-windows-msvc --features build-x64
