name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  build-native:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ubuntu-latest
            target: x64
          - image: windows-latest
            target: x64
          - image: windows-11-arm
            target: arm64
    runs-on: ${{ matrix.image }}
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
          rust-native: ${{ matrix.target }}
      - run: task run-build
      - uses: Pistonight/mono-dev/actions/rust-xplat@main
        with:
          arch: ${{ matrix.target }}
          binary: shaft
  build-windows-arm-x64:
    runs-on: windows-11-arm
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
          rust-native: arm64
      - run: task run-build
      - run: cargo build --bin shaft --release --target x86_64-pc-windows-msvc --feature build-x64
